/* AUTOGENERATED FILE - DO NOT EDIT CONTENTS */

export const projectId = "xlnzsryiimdkxnudmdoo"
export const publicAnonKey = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InhsbnpzcnlpaW1ka3hudWRtZG9vIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTc3MzUxMTksImV4cCI6MjA3MzMxMTExOX0.FH7lyev8ehSeUe_Z_gCXn5xkCB--Uv__sF8UK7U-e0Y"